language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tmt' ]; then cd .. && eval "mv $currentfolder generator-tmt" && cd generator-tmt; fi

